defaults:
  - env/train: PutOnPlateInScene25Main
  - env/eval: maniskill_ood_template
  - model/openvla_oft@actor.model
  - training_backend/fsdp@actor.fsdp_config
  - override hydra/job_logging: stdout

hydra:
  run:
    dir: .
  output_subdir: null
  searchpath:
    - file://${oc.env:EMBODIED_PATH}/config/
    
cluster:
  num_nodes: 1
  component_placement:
    actor: 0-7
    env: 0-7
    rollout: 0-7

runner:
  task_type: embodied
  logger:
    log_path: "../results"
    project_name: rlinf
    experiment_name: "test_openvla"
    logger_backends: ["tensorboard"] # wandb, swanlab

  max_epochs: 1000
  max_steps: -1

  only_eval: False
  eval_policy_path: null
  val_check_interval: -1
  save_interval: 40
  seq_length: 4096
  max_prompt_length: 30

  resume_dir: null

algorithm:
  normalize_advantages: True
  kl_penalty: kl  # how to estimate kl divergence: kl or kl_penalty
  group_size: 8

  rollout_epoch: 1
  eval_rollout_epoch: 1 # set eval_rollout_epoch > 0 when enable runner.only_eval or runner.val_check_interval > 0

  reward_type: action_level  # action_level or chunk_level
  logprob_type: token_level
  entropy_type: token_level

  adv_type: grpo
  loss_type: actor
  loss_agg_func: "token-mean"
  kl_beta: 0.0
  entropy_bonus: 0
  clip_ratio_high: 0.28
  clip_ratio_low: 0.2
  clip_ratio_c: 3.0
  value_clip: 0.2
  huber_delta: 10.0

  gamma: 0.99
  gae_lambda: 0.95

  # params for rollout
  sampling_params:
    use_greedy: False
    temperature_train: 1.0
    temperature_eval: 0.6
    top_k: 0
    top_p: 1.0
    repetition_penalty: 1.0

  # length argument for autoregressive sampling
  # max length means max amount of tokens to generate
  length_params:
    max_new_token: null
    max_length: 1024
    min_length: 1

env:
  group_name: "EnvGroup"
  enable_offload: False

  # Override the default values in env/train or env/eval
  train:
    total_num_envs: 256
    group_size: ${algorithm.group_size}

rollout:
  group_name: "RolloutGroup"
  generation_backend: "huggingface"
  enable_offload: True
  pipeline_stage_num: 1

  model:
    model_path: "/path/to/model/Openvla-oft-SFT-libero10-trajall/"
    precision: ${actor.model.precision}

actor:
  group_name: "ActorGroup"
  training_backend: "fsdp"
  micro_batch_size: 40
  global_batch_size: 640
  seed: 1234
  enable_offload: True

  # Override the default values in model/openvla_oft
  model:
    model_path: "/path/to/model/Openvla-oft-SFT-libero10-trajall/"
    model_type: "openvla_oft"

    unnorm_key: bridge_orig
    is_lora: True
    lora_path: /path/to/model/oft-sft/lora_004000

  tokenizer:
    tokenizer_type: "HuggingFaceTokenizer"
    tokenizer_model: "/path/to/model/Openvla-oft-SFT-libero10-trajall/"
    use_fast: False
    trust_remote_code: True
    padding_side: "right"

  optim:
    lr: 1.0e-4
    value_lr: 3.0e-3
    adam_beta1: 0.9
    adam_beta2: 0.999
    adam_eps: 1.0e-05
    clip_grad: 10.0

  # Override the default values in training_backend/fsdp
  fsdp_config:
    strategy: "fsdp"
    gradient_checkpointing: True
    mixed_precision:
      param_dtype: ${actor.model.precision}
      reduce_dtype: ${actor.model.precision}
      buffer_dtype: ${actor.model.precision}

reward:
  use_reward_model: False

critic:
  use_critic_model: False