simulator_type: behavior
total_num_envs: null
auto_reset: False
ignore_terminations: False
use_rel_reward: True
seed: 0
group_size: 1
use_fixed_reset_state_ids: False
max_episode_steps: 2000
max_steps: 2000
only_eval: False
image_size: [224, 224]

video_cfg:
  save_video: False
  info_on_video: True
  video_base_dir: ${runner.logger.log_path}/video/train

base_config_name: r1pro_behavior

tasks:
  activity_task_indices: "0" # eg. "0-49" or "0-20,49"
  task_idx: 0
  task_description_path: examples/embodiment/config/env/behavior_task.jsonl
