simulator_type: isaaclab
task_type: stack_cube

total_num_envs: null

auto_reset: True
ignore_terminations: True
max_episode_steps: 10

use_rel_reward: True
reward_coef: 1.0
only_eval: True
group_size: 1
use_fixed_reset_state_ids: True

video_cfg:
  save_video: True
  info_on_video: True
  video_base_dir: ${runner.logger.log_path}/video/eval

init_params:
  id: "Isaac-Stack-Cube-Franka-IK-Rel-Visuomotor-Cosmos-v0"
  num_envs: null 
  max_episode_steps: ${env.eval.max_episode_steps}
  task_description: "Stack three cubes (bottom to top: blue, red, green) with the Franka robot."
  table_cam:
    height: 256
    width: 256
  wrist_cam:
    height: 256
    width: 256