simulator_type: libero
task_suite_name: libero_10

total_num_envs: null

auto_reset: True
ignore_terminations: True
max_episode_steps: 512
use_fixed_reset_state_ids: True
use_ordered_reset_state_ids: True

use_rel_reward: True
reward_coef: 5.0
only_eval: True

seed: 0
group_size: 1

num_envs: 16

video_cfg:
  save_video: True
  info_on_video: True
  video_base_dir: ${runner.logger.log_path}/video/eval

init_params:
  camera_heights: 256
  camera_widths: 256