simulator_type: maniskill

total_num_envs: null

auto_reset: True
ignore_terminations: True
use_rel_reward: True
seed: 0
group_size: 1
policy_setup: "windwox_bridge"
use_fixed_reset_state_ids: True
only_eval: True
max_episode_steps: 80

video_cfg:
  save_video: True
  info_on_video: True
  video_base_dir: ${runner.logger.log_path}/video/eval

init_params:
  id: "PutOnPlateInScene25Main-v3"
  num_envs: null # will be set when ManiskillEnv init
  obs_mode: "rgb+segmentation"
  control_mode: None
  sim_backend: "gpu"
  sim_config:
    sim_freq: 500
    control_freq: 5
  max_episode_steps: ${env.eval.max_episode_steps}
  sensor_configs:
    shader_pack: "default"
  render_mode: sensors
  obj_set: train