simulator_type: maniskill

total_num_envs: null

auto_reset: True
ignore_terminations: True
use_rel_reward: True
reward_mode: raw
seed: 0
group_size: 1
use_fixed_reset_state_ids: True
max_episode_steps: 50
only_eval: True

video_cfg:
  save_video: True
  info_on_video: True
  video_base_dir: ${runner.logger.log_path}/video/eval

init_params:
  id: "PickCube-v1"
  num_envs: null # will be set in ManiSkillEnv init
  obs_mode: "state"
  control_mode: None
  sim_backend: "gpu"
  sim_config:
    sim_freq: 100
    control_freq: 20
  max_episode_steps: ${env.eval.max_episode_steps}
  sensor_configs:
    shader_pack: "default"
  render_mode: all